version: 2
jobs:
  build_docker:
    machine:
      docker_layer_caching: true
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            docker pull coderrect/openrace-env
            pwd
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build . --parallel
            ctest
    persist_to_workspace:
      root: .
      paths: 
       - bin
       - DartConfiguration.tcl
  test:
    docker: 
     - image: coderrect/openrace-env
    steps:
     - attach_workspace:
        at: .
     - run: ctest --parallel $(nproc)
    
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build