jobs:
  build:
    docker: 
      - image: coderrect/openrace-env
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build .
            ctest
