version: 2.1
executors:
  docker-publisher:
    docker:
      - image: coderrect/openrace-env:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup cmake and build artifacts
          command: |
            pwd
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build .
            ctest
  test:
    docker: 
     - image: coderrect/openrace-env
    steps:
     - attach_workspace:
        at: .
     - run: ctest --parallel $(nproc)
    
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build