version: 2
jobs:
  build:
    docker:
        - image: coderrect/openrace-env
    steps:
      - checkout
      - run:
          name: Build artifacts 
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build .
            ctest
          
    persist_to_workspace:
      root: .
      paths: 
       - bin
       - DartConfiguration.tcl
  test:
    docker: 
     - image: coderrect/openrace-env
    steps:
     - attach_workspace:
        at: .
     - run: ctest
    
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build