version: 2

jobs:
  build:
    docker:
      - image: coderrect/openrace-env
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            pwd
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build . --parallel 2
            ctest --parallel 2
      - store_artifacts:
          path: build/testresults
      - store_test_results:
          path: build/testresults


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
