name: codecov

on:
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/codecov.yml'
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  codecov:
    runs-on: ubuntu-latest
    container: coderrect/openrace-env

    steps:
      - uses: actions/checkout@v2

      - name: install gcc-10
        run: |
          apt-get -y update
          apt-get install -y g++-10

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-10 -DCODE_COVERAGE=On -DLLVM_INSTALL=/usr/local ..
          cmake --build . --parallel
      
      - name: Run Tests
        run: |
          cd build
          ctest --parallel $(nproc)

      - name: Generate Coverage Report
        run: |
          apt-get -y update
          apt-get install -y lcov
          cd build
          lcov --directory . --capture --output-file openrace-coverage-full.info
          lcov --remove openrace-coverage-full.info "*/tests/*" -o openrace-coverage.info

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./build/openrace-coverage.info 
          verbose: true